version: '3'
services:
  ionic-app:
    build: .
    environment:
      - VIRTUAL_HOST=tts-milesight.irritec.com
      - LETSENCRYPT_HOST=tts-milesight.irritec.com
      - LETSENCRYPT_EMAIL=tuo@email.it
    networks:
      - webproxy
    restart: always

networks:
  webproxy:
    external: true
